name: Validate PR Labeler Configuration
on:
  push: {}
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Configuration
        uses: Yash-Singh1/pr-labeler-config-validator@releases/v0.0.3
        with:
          configuration-path: .github/pr-labeler.yml
